apiVersion: batch/v1
kind: Job
metadata:
  name: cfdwid-lr-inference
spec:
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: cfdwid-lr-inference
          image: jkieley/cfdwid_lr_inference
          env:
            - name: INPUT_CSV_FILE_PATH
              value: /app/mnt/creditcard_large.csv
            - name: TRAINED_OUTPUT_MODEL_PATH
              value: {{trainedOutputModelPath}}
          volumeMounts:
            - mountPath: /app/mnt
              name: test-volume
          resources:
            limits:
              memory: "2500Mi"
              cpu: "2"
            requests:
              memory: "2500Mi"
              cpu: "2"
      volumes:
        - name: test-volume
          hostPath:
            path: /to-mount-data-dir
            type: Directory
      restartPolicy: Never
  backoffLimit: 1
